let database = [
	{
		id: '1',
		subject: 'Vue',
		tags: 'Vue, Quasar',
		hours: 15,
		account: 'HY',
		title: 'PWA with Vue JS, Quasar & Firebase (with NodeJS & Express)',
		url: 'https://www.udemy.com/course/pwa-with-vuejs-quasar-firebase/learn/lecture/20492130#overview',
	},
	{
		id: '2',
		subject: 'Next',
		tags: 'React, Next',
		hours: 13,
		account: 'SP',
		title: 'Next.JS with Sanity CMS - Serverless Blog App (w/ Vercel)',
		url: 'https://www.udemy.com/course/nextjs-with-sanity-cms-serverless-blog-app-w-vercel/learn/lecture/20359909#overview',
	},
	{
		id: '3',
		subject: 'Gatsby',
		tags: 'React, Gatsby, GraphQL',
		hours: 38,
		account: 'SP',
		title: 'Gatsby Tutorial and Projects Course',
		url: 'https://www.udemy.com/course/gatsby-tutorial-and-projects-course/learn/lecture/14891808#overview',
	},

	{
		id: '4',
		subject: 'React',
		tags: 'React, Serverless',
		hours: 7,
		account: 'SP',
		title: 'React and Serverless - Fullstack Web Development Your progress',
		url: 'https://www.udemy.com/course/react-and-serverless/learn/lecture/20008686?start=0#overview',
	},
	{
		id: '5',
		subject: 'GraphQL',
		tags: 'React, GraphQL, Node',
		hours: 19,
		account: 'HY',
		title: 'GraphQL from Scratch - Realtime MERN Stack with React Node',
		url: 'https://www.udemy.com/course/graphql-react-node/learn/lecture/19711874?start=0#overview',
	},
	{
		id: '6',
		subject: 'Gatsby',
		tags: 'React, Strapi',
		hours: 28,
		account: 'SP',
		title: 'The Complete Strapi Course',
		url: 'https://www.udemy.com/course/the-complete-strapi-course/learn/lecture/20153090#overvieww',
		current: true,
	},
	{
		id: '7',
		subject: 'ReactInt',
		tags: 'React',
		hours: 51,
		account: 'HY',
		title: 'React Tutorial and Projects Course',
		url: 'https://www.udemy.com/course/react-tutorial-and-projects-course/learn/lecture/12499178?start=0#overview',
	},
	{
		id: '8',
		subject: 'Gatsby',
		tags: 'React, Gatsby',
		hours: 2,
		account: 'YT',
		title: 'Build an Ecommerce Site Using Stripe and Gatsby',
		url: 'https://www.youtube.com/watch?v=g4aCBNt5Pcg',
	},

	{
		id: '9',
		subject: 'React',
		tags: 'React, React Native',
		hours: 18,
		account: 'MI',
		title: 'تعلم React Native',
		url: 'https://www.udemy.com/course/react-native-m/learn/lecture/20058580?start=15#questions',
	},
	{
		id: '10',
		subject: 'React',
		tags: 'React, Optimization',
		hours: 6,
		account: 'SP',
		title: 'The Complete Guide to Advanced React Component Patterns',
		url: 'https://www.udemy.com/course/the-complete-guide-to-advanced-react-patterns/learn/lecture/17200022#overview',
	},
	{
		id: '11',
		subject: 'ReactInt',
		tags: 'React',
		hours: 40,
		account: 'MI',
		title: 'Complete React Developer in 2020 (w/ Redux, Hooks, GraphQL)',
		url: 'https://www.udemy.com/course/complete-react-developer-zero-to-mastery/learn/lecture/14870615?start=0#overview',
	},
	{
		id: '12',
		subject: 'React',
		tags: 'React, Material UI',
		hours: 41,
		account: 'SP',
		title: 'Implement High Fidelity Designs with Material-UI and ReactJS',
		url: 'https://www.udemy.com/course/implement-high-fidelity-designs-with-material-ui-and-reactjs/learn/lecture/16234402?start=165#overview',
	},
	{
		id: '13',
		subject: 'React',
		tags: 'React, Optimization',
		hours: 9,
		account: 'SP',
		title: 'Advanced React (Render Performance Best Practices Patterns)',
		url: 'https://www.udemy.com/course/advanced-react-render-performance-best-practices-patterns/learn/lecture/19653114#overview',
	},
	{
		id: '14',
		subject: 'ReactInt',
		tags: 'React',
		hours: 11,
		account: 'SP',
		title: 'React 边做边学（从零开始，包含Hooks',
		url: 'https://www.udemy.com/course/react-lean-by-doing/learn/lecture/16800324?start=512#overview',
	},
	{
		id: '15',
		subject: 'Next',
		tags: 'React, Next',
		hours: 2,
		account: 'SP',
		title: 'Next JS with React Hooks - Building SSR React Applications',
		url: 'https://www.udemy.com/course/next-js-react-hooks/learn/lecture/14095110?start=0#overview',
		completed: true,
	},
	{
		id: '16',
		subject: 'React',
		tags: 'React, Node',
		hours: 14,
		account: 'SP',
		title: 'React Front To Back',
		url: 'https://www.udemy.com/course/modern-react-front-to-back/learn/lecture/14969812?start=174#overview',
	},
	{
		id: '17',
		subject: 'ReactInt',
		tags: 'React',
		hours: 9,
		account: 'SP',
		title: 'React Hooks 入門 - Hooksと Redux を組み合わせて最新のフロントエンド状態管理手法を習得しよう！',
		url: 'https://www.udemy.com/course/react-hooks-101/learn/lecture/15049578?start=0#overview',
	},
	{
		id: '18',
		subject: 'React',
		tags: 'React, Styled Components',
		hours: 7,
		account: 'SP',
		title: 'React Styled Components Tutorial and Project Course',
		url: 'https://www.udemy.com/course/styled-components-tutorial-and-project-course/learn/lecture/15328098?start=15#overview',
	},
	{
		id: '19',
		subject: 'ReactInt',
		tags: 'React, Styled Components',
		hours: 41,
		account: 'SP',
		title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
		url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/learn/lecture/13556330#overview',
	},
	{
		id: '20',
		subject: 'ReactInt',
		tags: 'React',
		hours: 16,
		account: 'SP',
		title: 'React For The Rest Of Us',
		url: 'https://www.udemy.com/course/react-for-the-rest-of-us/learn/lecture/18081709#overview',
	},
	{
		id: '21',
		subject: 'ReactInt',
		tags: 'React, Node, MERN',
		hours: 43,
		account: 'SP',
		title: 'De cero a experto ( Hooks y MERN )',
		url: 'https://www.udemy.com/course/react-cero-experto/learn/lecture/19751074?start=0#announcements',
	},
	{
		id: '22',
		subject: 'ReactInt',
		tags: 'React, Node, MERN',
		hours: 41,
		account: 'SP',
		title: 'React - La Guía Completa: Hooks Context Redux MERN +15 Apps',
		url: 'https://www.udemy.com/course/react-de-principiante-a-experto-creando-mas-de-10-aplicaciones/learn/lecture/17666784?start=0#announcements',
	},
	{
		id: '23',
		subject: 'Gatsby',
		tags: 'React, Gatsby, GraphQL, Wordpress, PWA',
		hours: 4,
		account: 'HY',
		title: 'Gatsby JS: Build PWA Blog With GraphQL And React + WordPress',
		url: 'https://www.udemy.com/course/gatsby-js-build-pwa-blog-with-graphql-and-react-wordpress/learn/lecture/15158236?start=0#overview',
	},
	{
		id: '24',
		subject: 'React',
		tags: 'React, GraphQL, Wordpress',
		hours: 5,
		account: 'HY',
		title: 'Build a Realtime App with React Hooks and GraphQL',
		url: 'https://www.udemy.com/course/build-a-realtime-app-with-react-hooks-and-graphql/learn/lecture/13747756#overview',
	},
	{
		id: '25',
		subject: 'ReactInt',
		tags: 'React, Angular, Node',
		hours: 80,
		account: 'HY',
		title: 'React, Angular, Node In-Depth Guide: Beginner to Pro (2020)',
		url: 'https://www.udemy.com/course/react-angular-node-in-depth-guide-beginner-to-pro-2020/learn/lecture/18569676?start=0#overview',
	},
	{
		id: '26',
		subject: 'Next',
		tags: 'React, Next, Node, GraphQL, Apollo',
		hours: 29,
		account: 'HY',
		title: 'Next.js and Apollo - Portfolio App (w/ React, GraphQL, Node)',
		url: 'https://www.udemy.com/course/nextjs-and-apollo-portfolio-app-w-react-graphql-node/learn/lecture/18742898?start=0#overview',
	},
	{
		id: '27',
		subject: 'Vue',
		tags: 'Vue',
		hours: 18,
		account: 'SP',
		title: '超Vue.js 完全パック - もう他の教材は買わなくてOK！ (Vue Router, Vuex含む)',
		url: 'https://www.udemy.com/course/vue-js-complete-guide/learn/lecture/15370946?#overview',
	},
	{
		id: '28',
		subject: 'Javascript',
		tags: 'Javascript, PWA',
		hours: 16,
		account: 'HY',
		title: 'Progressive Web Apps (PWA) - The Complete Guide',
		url: 'https://www.udemy.com/course/progressive-web-app-pwa-the-complete-guide/learn/lecture/13914126#overview',
	},
	{
		id: '29',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 12,
		account: 'MI',
		title: 'JavaScript: Understanding the Weird Parts',
		url: 'https://www.udemy.com/course/understand-javascript/learn/lecture/2237542?start=0#overview',
	},
	{
		id: '30',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 25,
		account: 'MI',
		title: 'JavaScript: The Advanced Concepts',
		url: 'https://www.udemy.com/course/advanced-javascript-concepts/learn/lecture/13772854#overview',
	},
	{
		id: '31',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 32,
		account: 'MI',
		title: 'JavaScript Web Projects: 20 Projects to Build Your Portfolio',
		url: 'https://www.udemy.com/course/javascript-web-projects-to-build-your-portfolio-resume/learn/lecture/19961158?start=0#overview',
	},
	{
		id: '32',
		subject: 'Javascript',
		tags: 'Javascript, React',
		hours: 8,
		account: 'HY',
		title: 'JavaScript Master Class - Build your own React from scratch',
		url: 'https://www.udemy.com/course/javascript-deep-dive-code-your-own-react-library/learn/lecture/12102042?start=60#overview',
	},
	{
		id: '33',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 21,
		account: 'SP',
		title: '【JS】初級者から中級者になるためのJavaScriptメカニズム',
		url: 'https://www.udemy.com/course/javascript-essence/learn/lecture/19799294?start=0#overview',
	},
	{
		id: '34',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 20,
		account: 'SP',
		title: 'Master the Coding Interview: Data Structures + Algorithms',
		url: 'https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/learn/lecture/12133484?start=120#overview',
	},
	{
		id: '35',
		subject: 'Javascript',
		tags: 'Javascript, Typescript',
		hours: 25,
		account: 'CE',
		title: "Typescript: The Complete Developer's Guide [2020]",
		url: 'https://www.udemy.com/course/typescript-the-complete-developers-guide/learn/lecture/14504488?start=0#overview',
		current: true,
	},
	{
		id: '36',
		subject: 'Javascript',
		tags: 'Javascript, Typescript',
		hours: 16,
		account: 'SP',
		title: '【世界で7万人が受講】Understanding TypeScript - 2020年最新版',
		url: 'https://www.udemy.com/course/understanding-typescript-jp/learn/lecture/18184848?start=0#overview',
	},
	{
		id: '37',
		subject: 'Javascript',
		tags: 'Javascript, Typescript',
		hours: 17,
		account: 'SP',
		title: 'ハンズオンで学ぶ TypeScript - JavaScript エンジニアのための TypeScript徹底入門',
		url: 'https://www.udemy.com/course/ts-for-js-developers/learn/lecture/21394194#overview',
	},
	{
		id: '38',
		subject: 'Node',
		tags: 'Serverless, React, AWS',
		hours: 8,
		account: 'HY',
		title: 'Build a Serverless App with AWS Lambda - Hands On!',
		url: 'https://www.udemy.com/course/build-a-serverless-app-with-aws-lambda-hands-on/learn/lecture/11863430#overview',
	},

	{
		id: '39',
		subject: 'Javascript',
		tags: 'Javascript, Optimization',
		hours: 8,
		account: 'CE',
		title: '*NEW* Web Development Secrets 2020 - CRP, HTTP, AJAX & More',
		url: 'https://www.udemy.com/course/new-web-development-secrets/learn/lecture/15578344?start=0#overview',
	},
	{
		id: '40',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 10,
		account: 'SP',
		title: '*NEW* DOM 2020 Build Dynamic Websites with JavaScript Part 2',
		url: 'https://www.udemy.com/course/build-dynamic-websites-dom-2/learn/lecture/17908964#overview',
	},
	{
		id: '41',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 22,
		account: 'CE',
		title: 'Modern JavaScript From The Beginning',
		url: 'https://www.udemy.com/course/modern-javascript-from-the-beginning/learn/lecture/8762504?start=0#overview',
	},

	{
		id: '42',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 16,
		account: 'SP',
		title: '20 Web Projects With Vanilla JavaScript',
		url: 'https://www.udemy.com/course/web-projects-with-vanilla-javascript/learn/lecture/17842028?start=210#overview',
	},
	{
		id: '43',
		subject: 'Node',
		tags: 'Serverless, React, AWS, GraphQL',
		hours: 11,
		account: 'HY',
		title: 'AWS AppSync & Amplify with React & GraphQL - Complete Guide!',
		url: 'https://www.udemy.com/course/aws-appsync-amplify-with-react-graphql-course/learn/lecture/16409720#overview',
	},

	{
		id: '44',
		subject: 'Javascript',
		tags: 'Javascript, Webpack',
		hours: 6,
		account: 'SP',
		title: 'Webpack 4: Beyond the Basics',
		url: 'https://www.udemy.com/course/webpack-beyond-the-basics/learn/lecture/8445416?start=285#overview',
	},
	{
		id: '45',
		subject: 'Node',
		tags: 'Chatbot, React, Node',
		hours: 10,
		account: 'HY',
		title: 'Create Chatbot for Website with React and Node.js',
		url: 'https://www.udemy.com/course/chatbot-for-website-with-react-and-nodejs/learn/lecture/10497038#overview',
	},
	{
		id: '46',
		subject: 'Javascript',
		tags: 'Javascript, Webpack',
		hours: 7,
		account: 'SP',
		title: 'LEARNING PATH: Webpack: Web Development with Webpack',
		url: 'https://www.udemy.com/course/learning-path-webpack-web-development-with-webpack/learn/lecture/9378330#overview',
	},
	{
		id: '47',
		subject: 'Node',
		tags: 'Node',
		hours: 25,
		account: 'SP',
		title: 'The Complete Full-Stack JavaScript Course!',
		url: 'https://www.udemy.com/course/full-stack-javascript/learn/lecture/14022702?start=0#overview',
	},

	{
		id: '48',
		subject: 'Node',
		tags: 'Node, MongoDB',
		hours: 18,
		account: 'HY',
		title: "MongoDB - The Complete Developer's Guide 2020",
		url: 'https://www.udemy.com/course/mongodb-the-complete-developers-guide/learn/lecture/13914002?start=0#overview',
	},
	{
		id: '49',
		subject: 'Node',
		tags: 'Node, Electron, React',
		hours: 6,
		account: 'SP',
		title: 'Electron From Scratch: Build Desktop Apps With JavaScript',
		url: 'https://www.udemy.com/course/electron-from-scratch/learn/lecture/19823412#overview',
	},
	{
		id: '50',
		subject: 'Node',
		tags: 'Node',
		hours: 35,
		account: 'MI',
		title: 'The Complete Node.js Developer Course (3rd Edition)',
		url: 'https://www.udemy.com/course/the-complete-nodejs-developer-course-2/learn/lecture/13729190?start=0#announcements',
	},
	{
		id: '51',
		subject: 'Node',
		tags: 'Node, API',
		hours: 12,
		account: 'CE',
		title: 'Node.js API Masterclass With Express & MongoDB Your progress',
		url: 'https://www.udemy.com/course/nodejs-api-masterclass/learn/lecture/16581402?start=0#overview',
	},
	{
		id: '52',
		subject: 'Node',
		tags: 'Node',
		hours: 40,
		account: 'SP',
		title: 'NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)',
		url: 'https://www.udemy.com/course/nodejs-the-complete-guide/learn/lecture/11561886#overview',
	},
	{
		id: '53',
		subject: 'Node',
		tags: 'Node',
		hours: 42,
		account: 'SP',
		title: 'Node.js, Express, MongoDB & More: The Complete Bootcamp 2020',
		url: 'https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/learn/lecture/15065290?start=135#overview',
	},
	{
		id: '54',
		subject: 'Node',
		tags: 'Node',
		hours: 32,
		account: 'HY',
		title: 'nodejs 2020 中文全系列教程',
		url: 'https://www.udemy.com/course/nodejs-2020/learn/lecture/19475016?start=315#overview',
	},
	{
		id: '55',
		subject: 'Node',
		tags: 'Node',
		hours: 16,
		account: 'HY',
		title: 'Node JS: Advanced Concepts',
		url: 'https://www.udemy.com/course/advanced-node-for-developers/learn/lecture/9667538?start=0#overview',
	},
	{
		id: '56',
		subject: 'Node',
		tags: 'Node, React',
		hours: 27,
		account: 'MI',
		title: 'Learn JavaScript: Full-Stack from Scratch',
		url: 'https://www.udemy.com/course/learn-javascript-full-stack-from-scratch/learn/lecture/15373818?start=1#overview',
	},
	{
		id: '57',
		subject: 'Css',
		tags: 'Css, UX, UI',
		hours: 12,
		account: 'HY',
		title: 'User Experience (UX): The Ultimate Guide to Usability and UX',
		url: 'https://www.udemy.com/course/ultimate-guide-to-ux/learn/lecture/218133#overview',
	},

	{
		id: '58',
		subject: 'Css',
		tags: 'Css',
		hours: 21,
		account: 'SP',
		title: 'Modern HTML & CSS From The Beginning (Including Sass)',
		url: 'https://www.udemy.com/course/modern-html-css-from-the-beginning/learn/lecture/13285606?start=0#overview',
	},
	{
		id: '59',
		subject: 'Css',
		tags: 'Css, Materialize',
		hours: 11,
		account: 'SP',
		title: 'Materialize CSS From Scratch With 5 Projects',
		url: 'https://www.udemy.com/course/materialize-css-from-scratch-with-5-projects/learn/lecture/9380778?start=120#overview',
	},
	{
		id: '60',
		subject: 'Css',
		tags: 'Css, UI, IX, Design',
		hours: 21,
		account: 'SP',
		title: 'UI UX Design Hybrid Course — Master Web Development with CSS',
		url: 'https://www.udemy.com/course/uxdevelopment/learn/lecture/21499324?start=45#questions',
	},
	{
		id: '61',
		subject: 'Css',
		tags: 'Css, UI, IX, Design',
		hours: 4,
		account: 'CE',
		title: 'Level Up Your CSS Animation Skills',
		url: 'https://www.udemy.com/course/level-up-your-css-animation-skills/learn/lecture/14278658?start=746#overview',
	},
	{
		id: '62',
		subject: 'Css',
		tags: 'Css',
		hours: 28,
		account: 'SP',
		title: 'Advanced CSS and Sass: Flexbox, Grid, Animations and More!',
		url: 'https://www.udemy.com/course/advanced-css-and-sass/learn/lecture/8859760?start=150#overview',
	},
	{
		id: '63',
		subject: 'Css',
		tags: 'Css',
		hours: 7,
		account: 'CE',
		title: 'CSS Animations: The Complete Guide',
		url: 'https://www.udemy.com/course/css-animations-the-complete-guide/learn/lecture/21508866?start=0#overview',
	},
	{
		id: '64',
		subject: 'Css',
		tags: 'Css',
		hours: 6,
		account: 'CE',
		title: 'HTML, CSS, JavaScript - Build 6 Creative Projects',
		url: 'https://www.udemy.com/course/html-css-javascript-course-build-6-creative-projects/learn/lecture/12194674?start=180#overview',
	},
	{
		id: '65',
		subject: 'Css',
		tags: 'Css',
		hours: 2,
		account: 'CE',
		title: 'Creative CSS and Javascript Effects and Animation',
		url: 'https://www.udemy.com/course/creative-css-and-javascript-effects-and-animation/learn/lecture/20827122#overview',
	},
	{
		id: '66',
		subject: 'Css',
		tags: 'Css',
		hours: 49,
		account: 'CE',
		title: 'The Modern Flexbox, Grid, Sass & Animations Developer Course',
		url: 'https://www.udemy.com/course/the-modern-flexbox-grid-sass-animations-developer-course/learn/lecture/20861738?start=15#questions',
		current: true,
	},
	{
		id: '67',
		subject: 'Css',
		tags: 'Css',
		hours: 39,
		account: 'CE',
		title: 'The Ultimate HTML5 Elements & CSS3 Properties BOOTCAMP',
		url: 'https://www.udemy.com/course/the-most-up-tp-date-html5-css3-level-1-essentials-with-100-challenges/learn/lecture/18515152?start=131#overview',
	},
	{
		id: '68',
		subject: 'Css',
		tags: 'Css',
		hours: 13,
		account: 'CE',
		title: 'Mega CSS Animation Course : 30 Projects Included',
		url: 'https://www.udemy.com/course/mega-css-animation-course/learn/lecture/15322532?start=0#overview',
	},
	{
		id: '69',
		subject: 'Css',
		tags: 'Css',
		hours: 5,
		account: 'CE',
		title: 'Build Responsive & Real World Websites in HTML5 CSS 3 & JS',
		url: 'https://www.udemy.com/course/build-responsive-real-world-websites-in-html5-css-3-js/learn/lecture/20595720?start=0#overview',
	},
	{
		id: '70',
		subject: 'Css',
		tags: 'Css',
		hours: 10,
		account: 'CE',
		title: 'Build website elements with Html 5 & Css 3- ( 25+ project )',
		url: 'https://www.udemy.com/course/build-website-elements-with-html-5-css-3-25-project/learn/lecture/8485378?start=360#overview',
	},
	{
		id: '71',
		subject: 'Css',
		tags: 'Css',
		hours: 11,
		account: 'CE',
		title: 'Build a real world responsive website with Html 5 css 3 & JS',
		url: 'https://www.udemy.com/course/build-a-real-world-responsive-website-with-html-5-css-3-js/learn/lecture/9007158?start=15#overview',
	},
	{
		id: '72',
		subject: 'Css',
		tags: 'Css',
		hours: 4,
		account: 'HY',
		title: 'Advance CSS Shapes: Next Generation Websites (2020 Edition)',
		url: 'https://www.udemy.com/course/mastering-native-css-shapes/learn/lecture/7168320?start=0#overview',
	},
	{
		id: '73',
		subject: 'Css',
		tags: 'Css',
		hours: 11,
		account: 'CE',
		title: 'Learn PSD to Responsive Parallax HTML 5 / CSS 3 Web Design',
		url: 'https://www.udemy.com/course/learn-psd-to-responsive-parallax-html-5-css-3-web-design/learn/lecture/12566652?start=0#overview',
	},
	{
		id: '74',
		subject: 'Css',
		tags: 'Design, UI, UX',
		hours: 19,
		account: 'HY',
		title: 'Adobe XD: UI & UX Design with 14 real world project 2020',
		url: 'https://www.udemy.com/course/adobe-xd-ui-ux-design-with-10-real-world-project-2020-tuto/learn/lecture/18412718?start=0#overview',
	},
	{
		id: '75',
		subject: 'Css',
		tags: 'Css',
		hours: 11,
		account: 'HY',
		title: 'Advance CSS Grid - Build 4 Major Responsive Websites (2020)',
		url: 'https://www.udemy.com/course/css-grid-the-complete-guide/learn/lecture/10099838?start=0#overview',
	},
	{
		id: '76',
		subject: 'Css',
		tags: 'Css',
		hours: 20,
		account: 'SP',
		title: '【JavaScript＆CSS】ガチで学びたい人のためのWEB開発徹底実践（フロントエンド編）',
		url: 'https://www.udemy.com/course/front-dev-tutorial/learn/lecture/17695216?start=477#overview',
	},
	{
		id: '77',
		subject: 'Css',
		tags: 'Css',
		hours: 19,
		account: 'MI',
		title: 'Sıfırdan Bootstrap 4',
		url: 'https://www.udemy.com/course/sifirdan-bootstrap-4/learn/lecture/15031248#overview',
	},

	{
		id: '78',
		subject: 'Php',
		tags: 'Wordpress',
		hours: 26,
		account: 'SP',
		title: 'Become a WordPress Developer: Unlocking Power With Code',
		url: 'https://www.udemy.com/course/become-a-wordpress-developer-php-javascript/learn/lecture/7076998?start=270#overvie',
	},
	{
		id: '79',
		subject: 'Webdev',
		tags: 'Webdev',
		hours: 36,
		account: 'SP',
		title: 'The Complete Junior to Senior Web Developer Roadmap (2020)',
		url: 'https://www.udemy.com/course/the-complete-junior-to-senior-web-developer-roadmap/learn/lecture/10409076?start=0#overview',
	},
	{
		id: '80',
		subject: 'Webdev',
		tags: 'Webdev',
		hours: 32,
		account: 'SP',
		title: '(Ken Cen出品)建網百科全書-使用 HTML,CSS,JS, jQuery,php,mySQL 建立網站',
		url: 'https://www.udemy.com/course/ken-cens/learn/lecture/5246918?start=30#overview',
	},
	{
		id: '81',
		subject: 'Node',
		tags: 'Node, API',
		hours: 3,
		account: 'SP',
		title: 'Node JS API Development for Beginners',
		url: 'https://www.udemy.com/course/node-js-api-tutorial/learn/lecture/13683140#overview',
	},
	{
		id: '82',
		subject: 'Node',
		tags: 'React, Node, AWS',
		hours: 25,
		account: 'HY',
		title: 'React Node AWS - Build infinitely Scaling MERN Stack App',
		url: 'https://www.udemy.com/course/mern-react-node-aws/learn/lecture/18082809#overview',
	},
	{
		id: '83',
		subject: 'React',
		tags: 'React, AWS',
		hours: 22,
		account: 'HY',
		title: 'Build a Modern React and Redux App with CircleCI CI/CD & AWS',
		url: 'https://www.udemy.com/course/build-a-modern-react-and-redux-app-with-circleci-cicd-aws/learn/lecture/19258746#overview',
	},

	{
		id: '84',
		subject: 'React',
		tags: 'React, Microservices, Node',
		hours: 54,
		account: 'SP',
		title: 'Microservices with Node JS and React',
		url: 'https://www.udemy.com/course/microservices-with-node-js-and-react/learn/lecture/19248060#overview',
	},
	{
		id: '85',
		subject: 'Vue',
		tags: 'Vue, Nuxt',
		hours: 1,
		account: 'HY',
		title: 'Nuxt.js - Blazing Fast Static Sites with Vue.js',
		url: 'https://www.udemy.com/course/introduction-nuxt-js/learn/lecture/19043778#overview',
	},
	{
		id: '86',
		subject: 'Next',
		tags: 'React, Next',
		hours: 30,
		account: 'HY',
		title: 'Server side rendering with Next + React',
		url: 'https://www.udemy.com/course/server-side-rendering-with-next-react/learn/lecture/15279966#overview',
	},
	{
		id: '87',
		subject: 'Next',
		tags: 'React, Next',
		hours: 60,
		account: 'HY',
		title: 'Complete Next.js with React & Node - Beautiful Portfolio App',
		url: 'https://www.udemy.com/course/awesome-nextjs-with-react-and-node-amazing-portfolio-app/learn/lecture/19974126#overview',
	},
	{
		id: '88',
		subject: 'Node',
		tags: 'SQL, MySQL, Node',
		hours: 20,
		account: 'HY',
		title: 'The Ultimate MySQL Bootcamp: Go from SQL Beginner to Expert',
		url: 'https://www.udemy.com/course/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert/learn/lecture/6912202#overview',
	},
	{
		id: '89',
		subject: 'Next',
		tags: 'Next, React, Node',
		hours: 21,
		account: 'HY',
		title: 'MERN React Node Next.js Multi User SEO Blogging Platform',
		url: 'https://www.udemy.com/course/react-node-nextjs-fullstack-multi-user-blogging-platform-with-seo/learn/lecture/15723824#overview',
	},
	{
		id: '90',
		subject: 'Node',
		tags: 'React, Node',
		hours: 19,
		account: 'HY',
		title: 'React, NodeJS, Express & MongoDB - The MERN Fullstack Guide',
		url: 'https://www.udemy.com/course/react-nodejs-express-mongodb-the-mern-fullstack-guide/learn/lecture/16808122#overview',
	},
	{
		id: '91',
		subject: 'React',
		tags: 'React, Node, Redux',
		hours: 15,
		account: 'YT',
		title: '日本一わかりやすいReact-Redux入門#1...講座の概要【ECアプリを作ろう】',
		url: 'https://www.youtube.com/watch?v=FBMA34gUsgw&list=PLX8Rsrpnn3IWavNOj3n4Vypzwb3q1RXhr&index=1',
		current: true,
	},
	{
		id: '92',
		subject: 'Next',
		tags: 'React, Next',
		hours: 5,
		account: 'YT',
		title: 'Mastering Next.js',
		url: 'https://www.youtube.com/watch?v=uQeidE2LA1s&list=PL6bwFJ82M6FXjyBTVi6WSCWin8q_g_8RR',
	},
	{
		id: '93',
		subject: 'Next',
		tags: 'React, Next, Typescript',
		hours: 14,
		account: 'HY',
		title: 'Using TypeScript with React',
		url: 'https://www.udemy.com/course/react-with-typescript/learn/lecture/14462244#overview',
	},
	{
		id: '94',
		subject: 'Gatsby',
		tags: 'React, Gatsby',
		hours: 5,
		account: 'YT',
		title: 'Gatsby JS - The Great Gatsby Bootcamp [Full Tutorial]',
		url: 'https://www.youtube.com/watch?v=8t0vNu2fCCM&t=10226s',
	},
	{
		id: '95',
		subject: 'Gatsby',
		tags: 'React, Gatsby',
		hours: 2,
		account: 'YT',
		title: 'Set Up a New Gatsby + Shopify Ecommerce Site',
		url: 'https://www.youtube.com/watch?v=JwKMOH9k7-o',
		current: true,
	},
	{
		id: '96',
		subject: 'Next',
		tags: 'React, Next',
		hours: 3,
		account: 'YT',
		title: 'Learn Next.js in One Video - Fundamentals of Next.js',
		url: 'https://www.youtube.com/watch?v=tt3PUvhOVzo&t=8113s',
	},
	{
		id: '97',
		subject: 'Next',
		tags: 'React, Next',
		hours: 2,
		account: 'YT',
		title: 'Next.js Crash Course - SSG, SSR, API Routes, and more',
		url: 'https://www.youtube.com/watch?v=q-sYloF3xKM',
	},
	{
		id: '98',
		subject: 'Next',
		tags: 'React, Next',
		hours: 9,
		account: 'YT',
		title: 'Next.js Tutorial',
		url: 'https://www.youtube.com/watch?v=7J4iL1HDshQ&list=PLYSZyzpwBEWSQsrukurP09ksi49H9Yj40',
	},
	{
		id: '99',
		subject: 'Next',
		tags: 'React, Next',
		hours: 5,
		account: 'YT',
		title: '【日本一わかりやすいNext.js入門】#1 講座の概要',
		url: 'https://www.youtube.com/watch?v=F77RUjHZEAc&list=PLX8Rsrpnn3IUGEyanrHYGjY1WOzNe7Jd-',
	},
	{
		id: '100',
		subject: 'React',
		tags: 'React, Redux',
		hours: 2,
		account: 'YT',
		title: 'Redux Tutorial -- Redux دورة تعلم',
		url: 'https://www.youtube.com/watch?v=cIf5GCv7sBo&list=PLtFbQRDJ11kFPIchLt4xI6sBVxFUK1PBD',
	},
	{
		id: '101',
		subject: 'Php',
		tags: 'Laravel, Php',
		hours: 5,
		account: 'YT',
		title: 'Laravel PHP Framework Tutorial - Full Course for Beginners (2019)',
		url: 'https://www.youtube.com/watch?v=ImtZ5yENzgE',
	},
	{
		id: '102',
		subject: 'GraphQL',
		tags: 'GraphQL',
		hours: 5,
		account: 'YT',
		title: 'How to GraphQL',
		url: 'https://www.howtographql.com/basics/0-introduction/',
		completed: true,
	},
	{
		id: '103',
		subject: 'GraphQL',
		tags: 'GraphQL, Next',
		hours: 1,
		account: 'YT',
		title: 'Building a GraphQL server in Next.js',
		url: 'https://www.youtube.com/watch?v=Hn5neKIfJs8',
	},

	{
		id: '104',
		subject: 'GraphQL',
		tags: 'GraphQL, Next',
		hours: 1,
		account: 'YT',
		title: 'GraphQL with Apollo and Next.js',
		url: 'https://www.youtube.com/watch?v=cDAtqywpRD0',
	},
	{
		id: '105',
		subject: 'GraphQL',
		tags: 'GraphQL, Hasura',
		hours: 2,
		account: 'DC',
		title: 'Frontend GraphQL Tutorial (Hasura)',
		url: 'https://hasura.io/learn/',
	},
	{
		id: '106',
		subject: 'GraphQL',
		tags: 'GraphQL, Next, DotCMS',
		hours: 2,
		account: 'YT',
		title: 'Build and deploy your Jamstack with NextJS and GraphQL',
		url: 'https://www.youtube.com/watch?v=zy7xr7TcqUo',
	},
	{
		id: '107',
		subject: 'Next',
		tags: 'GraphQL, Next',
		hours: 6,
		account: 'YT',
		title: 'Next.js Leigh Halliday',
		url: 'https://www.youtube.com/watch?v=QABkof8ygzI&list=PL8fumNHsC-3PqViUl9A5g0zk57acoCKnh',
	},
	{
		id: '108',
		subject: 'GraphQL',
		tags: 'GraphQL, Next, Apollo',
		hours: 1,
		account: 'YT',
		title: 'Apollo Client v3 Fullstack Next.js Setup with SSR + Nexus Schema',
		url: 'https://www.youtube.com/watch?v=y34ym0-KZ8A',
		completed: true,
	},
	{
		id: '109',
		subject: 'GraphQL',
		tags: 'GraphQL, Next, Apollo',
		hours: 1,
		account: 'YT',
		title: 'Build your own GraphQL Resume with Next.js, Apollo Server, and Nexus Schema. Part 1 / 2',
		url: 'https://www.youtube.com/watch?v=_HOp7hBEjp8&list=PL8fumNHsC-3PqViUl9A5g0zk57acoCKnh&index=8',
	},
	{
		id: '110',
		subject: 'GraphQL',
		tags: 'GraphQL, Next, Apollo',
		hours: 1,
		account: 'YT',
		title: 'Build your own GraphQL Resume with Next.js, Apollo Client, and Prism Code Highlighter. Part 2 / 2',
		url: 'https://www.youtube.com/watch?v=ZFTRyuLwqdQ&list=PL8fumNHsC-3PqViUl9A5g0zk57acoCKnh&index=9',
	},
	{
		id: '111',
		subject: 'GraphQL',
		tags: 'GraphQL, Node, Apollo',
		hours: 4,
		account: 'YT',
		title: 'GraphQL Full Course - Novice to Expert',
		url: 'https://www.youtube.com/watch?v=ed8SzALpx1Q&t=202s',
	},
	{
		id: '112',
		subject: 'React',
		tags: 'React, Redux',
		hours: 1,
		account: 'YT',
		title: 'Create React App + Redux Template - Getting Started',
		url: 'https://www.youtube.com/watch?v=xbgwyhHmCyU',
	},
	{
		id: '113',
		subject: 'GraphQL',
		tags: 'Next, GraphQL',
		hours: 2,
		account: 'YT',
		title: 'Setting Up Typescript Next.js Project (Awad-1)',
		url: 'https://www.youtube.com/watch?v=xbgwyhHmCyU',
	},
	{
		id: '114',
		subject: 'GraphQL',
		tags: 'Next, GraphQL',
		hours: 3,
		account: 'YT',
		title: 'TypeGraphQL (Awad-2)',
		url: 'https://www.youtube.com/watch?v=8yZImm2A1KE&list=PLN3n1USn4xlma1bBu3Tloe4NyYn9Ko8Gs',
	},
	{
		id: '115',
		subject: 'GraphQL',
		tags: 'React, GraphQL',
		hours: 2,
		account: 'YT',
		title: 'GraphQL With React & Apollo',
		url: 'https://www.youtube.com/watch?v=SEMTj8w04Z8&list=PLillGF-RfqbZrjw48EXLdM4dsOhURCLZx&index=2&t=0s',
	},
	{
		id: '116',
		subject: 'GraphQL',
		tags: 'React, GraphQL',
		hours: 9,
		account: 'YT',
		title: 'Build a Project with GraphQL, Node, MongoDB and React',
		url: 'https://www.youtube.com/watch?v=yvEEeKMuxn0&list=PL55RiY5tL51rG1x02Yyj93iypUuHYXcB_&index=2',
	},
	{
		id: '117',
		subject: 'GraphQL',
		tags: 'React, GraphQL',
		hours: 1,
		account: 'YT',
		title: 'Level 1 Apollo Client with React Preview',
		url: 'https://www.youtube.com/watch?v=Wi9WoJeDaeA&list=PLLnpHn493BHE3dfAnJLuGAoU-m5eg__KR',
	},
	{
		id: '118',
		subject: 'GraphQL',
		tags: 'React, GraphQL, Apollo',
		hours: 1,
		account: 'YT',
		title: 'React tutorial - Javascript - Apollo-Client 3 - with Star Wars GraphQL API',
		url: 'https://www.youtube.com/watch?v=_KbvVNFa7K0',
		completed: true,
	},
	{
		id: '119',
		subject: 'GraphQL',
		tags: 'React, GraphQL, Apollo',
		hours: 3,
		account: 'YT',
		title: 'Intro to Apollo Client 3.0',
		url: 'https://www.youtube.com/watch?v=ou0fEW1eRjc',
	},
	{
		id: '120',
		subject: 'GraphQL',
		tags: 'React, GraphQL, Apollo',
		hours: 1,
		account: 'YT',
		title: 'State Management in GraphQL using React Hooks & Apollo (SHRUTI KAPOOR - Software Engineer at PayPal)',
		url: 'https://www.youtube.com/watch?v=Y3jXNMhAy0U',
	},
	{
		id: '121',
		subject: 'GraphQL',
		tags: 'React, GraphQL, Apollo',
		hours: 1,
		account: 'YT',
		title: 'Apollo Link State in Less than 30 Minutes',
		url: 'https://www.youtube.com/watch?v=CnhHeSAAbRM',
	},
	{
		id: '122',
		subject: 'GraphQL',
		tags: 'React, GraphQL, Apollo, Node',
		hours: 5,
		account: 'YT',
		title: 'Full Stack Apollo GraphQL Tutorial',
		url: 'https://www.youtube.com/watch?v=h-ZCVUAzR-0&list=PLASldBPN_pkDUuOzyPotAkKmvwqyDoA0g',
	},
	{
		id: '123',
		subject: 'Gatsby',
		tags: 'Gatsby, React',
		hours: 4,
		account: 'YT',
		title: 'Build a Website With Gatsby',
		url: 'https://www.youtube.com/watch?v=3LdJEEYLhY8&list=PLASldBPN_pkASjaDYtNEU_KSU2gksvFHg',
	},
	{
		id: '124',
		subject: 'Next',
		tags: 'Next, React',
		hours: 15,
		account: 'YT',
		title: 'Fullstack React GraphQL TypeScript Tutorial',
		url: 'https://www.youtube.com/watch?v=I6ypD7qv3Z8&t=47963s',
	},
	{
		id: '125',
		subject: 'React',
		tags: 'Typescript, React',
		hours: 4,
		account: 'SP',
		title: 'Typescript with modern React (i.e. hooks, context, suspense)',
		url: 'https://www.udemy.com/course/typescript-with-react-hooks-and-context/learn/lecture/13790950#overview',
	},
	{
		id: '126',
		subject: 'React',
		tags: 'Typescript, React',
		hours: 4,
		account: 'YT',
		title: 'Using Typescript with modern React (i.e. hooks, context, suspense)',
		url: 'https://www.youtube.com/watch?v=BnIhk4igd8I',
	},
	{
		id: '127',
		subject: 'Vue',
		tags: 'Vue',
		hours: 3,
		account: 'YT',
		title: 'Learn Vue 3 for Beginners - Full 2020 Tutorial Course',
		url: 'https://www.youtube.com/watch?v=ZqgiuPt5QZo&t=945s',
	},
	{
		id: '128',
		subject: 'Vue',
		tags: 'Vue',
		hours: 1,
		account: 'YT',
		title: 'Vue 3 TypeScript Tutorial 2020 (With Vuex and Vue Router)! Get Started With Vue 3 And TypeScript!',
		url: 'https://www.youtube.com/watch?v=V9MmoBAezD8',
	},
	{
		id: '129',
		subject: 'Javascript',
		tags: 'Javascript',
		hours: 1,
		account: 'YT',
		title: 'Code your own YouTube app: YouTube API + HTML + CSS + JavaScript (full tutorial)',
		url: 'https://www.youtube.com/watch?v=9sWEecNUW-o',
	},
	{
		id: '130',
		subject: 'Node',
		tags: 'Node',
		hours: 1,
		account: 'YT',
		title: 'Build a YouTube API Proxy Server with node.js/express and a Filterable List with Vanilla JavaScript',
		url: 'https://www.youtube.com/watch?v=Q4RiI7bvpso',
	},
	{
		id: '131',
		subject: 'Laravel',
		tags: 'Laravel, Php',
		hours: 15,
		account: 'YT',
		title: 'Laravel 8 Tutorial',
		url: 'https://www.youtube.com/watch?v=Du2yB9htD8k&list=PLz_YkiqIHesvWMGfavV8JFDQRJycfHUvD&index=2',
	},
	{
		id: '132',
		subject: 'Laravel',
		tags: 'Laravel, Php',
		hours: 15,
		account: 'YT',
		title: 'Laravel 8 tutorial (step by step)',
		url: 'https://www.youtube.com/watch?v=54WJepj8siE&list=PL8p2I9GklV46dciS4GDzBFHBi0JVIbnzT&index=5',
	},
	{
		id: '133',
		subject: 'Gatsby',
		tags: 'Gatsby',
		hours: 1,
		account: 'YT',
		title: 'Gatsby Dynamic App Tutorial',
		url: 'https://www.youtube.com/watch?v=RVNC61rkFxw&t=657s',
	},
	{
		id: '134',
		subject: 'Gatsby',
		tags: 'Gatsby',
		hours: 1,
		account: 'YT',
		title: 'Gatsby - Full Tutorial for Beginners',
		url: 'https://www.youtube.com/watch?v=mHFAM0CXviE',
	},
	{
		id: '135',
		subject: 'Next',
		tags: 'Next, MongoDB',
		hours: 2,
		account: 'YT',
		title: 'Next.js and MongoDB',
		url: 'https://www.youtube.com/watch?v=WSr0GcBF7Ag&list=PL_kAgwZgMfWx0ToY-XKCcAm9JH5UlTA-W&index=3E',
	},
	{
		id: '136',
		subject: 'Next',
		tags: 'Next, Typescript, Stripe',
		hours: 1,
		account: 'YT',
		title: 'Getting started with Next.js, TypeScript, and Stripe',
		url: 'https://www.youtube.com/watch?v=sPUSu19tZHg',
	},
	{
		id: '137',
		subject: 'Vue',
		tags: 'Vue, Laravel',
		hours: 18,
		account: 'YT',
		title: 'Master Laravel with GraphQL, Vue.js and Tailwind',
		url: 'https://www.udemy.com/course/master-laravel-with-graphql-vuejs-and-tailwind/learn/lecture/21630536#overview',
	},
	{
		id: '138',
		subject: 'Laravel',
		tags: 'Laravel',
		hours: 7,
		account: 'YT',
		title: 'Laravel PHP Framework Tutorial - Full Course 6.5 Hours (2020)',
		url: 'https://www.youtube.com/watch?v=BXiHvgrJfkg&t=218s',
	},
	{
		id: '138',
		subject: 'Laravel',
		tags: 'Laravel',
		hours: 7,
		account: 'YT',
		title: 'Laravel 6 Tutorial for Beginners',
		url: 'https://www.youtube.com/watch?v=zckH4xalOns&list=PL4cUxeGkcC9hL6aCFKyagrT1RCfVN4w2Q',
	},

	{
		id: '140',
		subject: 'Gatsby',
		tags: 'Gatsby, Ghost',
		hours: 2,
		account: 'YT',
		title: 'Trying out GHOST nodejs CMS with Gatsbyjs',
		url: 'https://www.youtube.com/watch?v=Zp15AnZUZVY',
	},
	{
		id: '141',
		subject: 'Gatsby',
		tags: 'Gatsby, Ghost',
		hours: 2,
		account: 'YT',
		title: 'Let’s Learn Ghost on the Jamstack! (with Dave Darnes) — Learn With Jason',
		url: 'https://www.youtube.com/watch?v=pOGjVNC1sk4',
	},
	{
		id: '142',
		subject: 'Gatsby',
		tags: 'Gatsby, Shopify',
		hours: 3,
		account: 'YT',
		title: 'Set Up a New Gatsby + Shopify Ecommerce Site pt. 2',
		url: 'https://www.youtube.com/watch?v=n2Z3Uhf2UQ4',
	},
	{
		id: '143',
		subject: 'Node',
		tags: 'Node',
		hours: 4,
		account: 'YT',
		title: 'All the Node.js and Express you need in a single live',
		url: 'https://www.youtube.com/watch?v=0xbfcRUuEfc',
	},
	{
		id: '144',
		subject: 'Next',
		tags: 'Next',
		hours: 10,
		account: 'YT',
		title: 'Making Websites With Next.js And Strapi',
		url: 'https://www.youtube.com/watch?v=HANfPCP_g4o&list=PLUBR53Dw-Ef_oTLzPB3G5CdLWnGOSsec3',
		current: true,
	},
	{
		id: '145',
		subject: 'Next',
		tags: 'Next',
		hours: 2,
		account: 'YT',
		title: 'Aprendiendo NextJS, el framework de React con Server Side Rendering',
		url: 'https://www.youtube.com/watch?v=2jxc8DMzt0I',
	},
	{
		id: '146',
		subject: 'Node',
		tags: 'Node',
		hours: 30,
		account: 'YT',
		title: 'Node JS Master Playlist (All about Node JS)',
		url: 'https://www.youtube.com/watch?v=huhNc-aVoeo&list=PLIGDNOJWiL18Rh8ymQgXnIwtg_Qx0fkXf&index=84',
	},
	{
		id: '147',
		subject: 'Next',
		tags: 'Next',
		hours: 3,
		account: 'YT',
		title: 'NNext JS Building Apps with React',
		url: 'https://www.youtube.com/watch?v=9vt-gkKiKAg&list=PLIGDNOJWiL19vRa2fITxnBD4MUQpQZJB0',
	},
	{
		id: '148',
		subject: 'Next',
		tags: 'Next',
		hours: 1,
		account: 'YT',
		title: 'Next.js On AWS at React Live Online 2020',
		url: 'https://www.youtube.com/watch?v=fRcoFAxvIIM',
	},
	{
		id: '149',
		subject: 'Next',
		tags: 'Next',
		hours: 7,
		account: 'YT',
		title: '[NEW Course] - Next.js Mastery - Kickstart',
		url: 'https://www.youtube.com/watch?v=62H1PEasNc0&list=PLYxzS__5yYQmpzsVeR7-KnX2li19KZhxE',
	},
	{
		id: '150',
		subject: 'React',
		tags: 'React',
		hours: 7,
		account: 'YT',
		title: 'Redux with React for State Management',
		url: 'https://www.youtube.com/watch?v=aS4fLCOMg1o&list=PLIGDNOJWiL18X8gaUi-PQYaOSHc9OAtIN',
	},
	{
		id: '151',
		subject: 'React',
		tags: 'React',
		hours: 7,
		account: 'YT',
		title: 'React Hooks Crash Course',
		url: 'https://www.youtube.com/watch?v=HmOw-45vg80&list=PLIGDNOJWiL1_R13jIah044J5zHBWyT3L6',
	},
	{
		id: '152',
		subject: 'Gatsby',
		tags: 'Gatsby',
		hours: 1,
		account: 'YT',
		title: 'Gatsby JS Crash Course',
		url: 'https://www.youtube.com/watch?v=6YhqQ2ZW1sc',
	},

	{
		id: '153',
		subject: 'Gatsby',
		tags: 'Gatsby',
		hours: 1,
		account: 'YT',
		title: 'Beyond Static: Building Dynamic Apps with Gatsby [Webinar]',
		url: 'https://www.youtube.com/watch?v=BrBK4yxodXA',
	},
	{
		id: '154',
		subject: 'Gatsby',
		tags: 'Gatsby, Shopify',
		hours: 6,
		account: 'HY',
		title: 'Gatsby JS & Shopify: Gatsby ecommerce sites [Gatsby 2020]',
		url: 'https://www.udemy.com/course/gatsby-ecommerce-shopify/learn/lecture/18082225#overview',
	},
	{
		id: '155',
		subject: 'React',
		tags: 'React, Firebase',
		hours: 32,
		account: 'HY',
		title: 'The essential guide to Firebase with React',
		url: 'https://www.udemy.com/course/the-essential-guide-to-firebase-with-react/learn/lecture/20393215#overview',
	},
	{
		id: '156',
		subject: 'Gatsby',
		tags: 'Gatsby, Sanity',
		hours: 2,
		account: 'YT',
		title: 'Build a Portfolio Site with Sanity.io and Gatsby — Learn',
		url: 'https://www.youtube.com/watch?v=SLGkyodumKI',
	},
	{
		id: '157',
		subject: 'Gatsby',
		tags: 'Gatsby, Sanity',
		hours: 7,
		account: 'YT',
		title: 'Gatsby and Sanity.io',
		url: 'https://www.youtube.com/watch?v=5idNI1Qpy40&list=PLDlWc9AfQBfZDUtf2vQXAspzR-50eDpbZ',
	},
	{
		id: '158',
		subject: 'Node',
		tags: 'GrapoQL, Apollo',
		hours: 2,
		account: 'YT',
		title: 'GraphQL and Apollo with Andrew Mead (Live Stream)',
		url: 'https://www.youtube.com/watch?v=9fH7kzKK4Ng&list=PLDlWc9AfQBfbuQ9enQFFb2pmEgBHBDeo7',
	},
	{
		id: '159',
		subject: 'Node',
		tags: 'SQL',
		hours: 25,
		account: 'HY',
		title: 'Complete SQL + Databases Bootcamp: Zero to Mastery [2020]',
		url: 'https://www.udemy.com/course/complete-sql-databases-bootcamp-zero-to-mastery/learn/lecture/18295198#overview',
		current: true,
	},
	{
		id: '160',
		subject: 'Node',
		tags: 'SQL',
		hours: 27,
		account: 'HY',
		title: 'React Avanzado: Fullstack Next.js, Apollo, MongoDB y GraphQL',
		url: 'https://www.udemy.com/course/fullstack-react-graphql-y-apollo-de-principiante-a-experto/learn/lecture/19098334#overview',
		current: true,
	},
]
