let database = [
  {
    id: "1",
    subject: "Node",
    tags: "Node, MongoDB",
    hours: 42,
    account: "SP",
    title: "Node.js, Express, MongoDB & More: The Complete Bootcamp 2020",
    url: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/learn/lecture/15065290?start=135#overview",
  },
  {
    id: "2",
    subject: "React",
    tags: "React, Styled Components",
    hours: 7,
    account: "SP",
    title: "React Styled Components Tutorial and Project Course",
    url: "https://www.udemy.com/course/styled-components-tutorial-and-project-course/learn/lecture/15328098?start=15#overview",
  },
  {
    id: "3",
    subject: "React",
    tags: "Node",
    hours: 35,
    account: "MI",
    title: "The Complete Node.js Developer Course (3rd Edition)",
    url: "https://www.udemy.com/course/the-complete-nodejs-developer-course-2/learn/lecture/13729190?start=0#announcements",
  },
  {
    id: "4",
    subject: "React",
    tags: "React, Gatsby",
    hours: 38,
    account: "SP",
    title: "Gatsby Tutorial and Projects Course",
    url: "https://www.udemy.com/course/gatsby-tutorial-and-projects-course/learn/lecture/14891808#overview",
  },
]
